# Generated by Django 3.1.7 on 2021-09-23 20:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210923_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('GUARDIAN', 'Guardian'), ('COMMITTEE', 'Committee')], max_length=10), blank=True, default=list, size=4),
        ),
    ]
