# Generated by Django 3.1.13 on 2021-09-25 10:05

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210923_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('GUARDIAN', 'Guardian'), ('COMMITTEE', 'Committee'), ('STAFF', 'Staff')], max_length=10), blank=True, default=list, size=5),
        ),
        migrations.CreateModel(
            name='StaffMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staffmore', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
